Repository BE14-NoB/Pick, pull requests merged in 2025-04, with the labels that each got.

#297 Refactor: 게시글 삭제 메소드에 현재 회원 검증 추가 외 6건
  Pick/src/main/java/com/nob/pick/common/util/JwtUtil.java
  Pick/src/main/java/com/nob/pick/common/util/WebSecurity.java
  Pick/src/main/java/com/nob/pick/infrastructure/MemberServiceClient.java
  Pick/src/main/java/com/nob/pick/post/command/application/controller/CommandPostController.java
  Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostService.java
  Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostServiceImpl.java
  Pick/src/main/java/com/nob/pick/post/intro
  Pick/src/test/java/com/nob/pick/post/DeletePostTest.java
Labels: :sparkles: enhancement, 🔧 refactoring

#308 [member] refactor : 멤버 테이블 필드명 변경
  db/member/CreateDummyData.sql
  db/member/CreateMemberTable.sql
  db/member/SelectAllMembers.sql
  db/member/SelectMemberById.sql
Labels: 🔧 refactoring

#310 [Refactor] member / 멤버 도메인 관련 필드명 변경
  README.md
  kick-member/src/main/java/com/nob/kickmember/member/command/entity/Member.java
  kick-member/src/main/java/com/nob/kickmember/member/query/dto/MemberDTO.java
  kick-member/src/main/resources/com/nob/kickmember/member/query/mapper/MemberMapper.xml
  kick-member/src/test/java/com/nob/kickmember/member/query/service/MemberServiceTest.java
Labels: 🔧 refactoring

#315 [Refactor] challenge, dailymission, badge / 챌린지 관련 도메인 멤버 연결 분리 및 뱃지 부여 기능 리팩토링
  Pick/src/main/java/com/nob/pick/Badge/command/application/controller/BadgeController.java
  Pick/src/main/java/com/nob/pick/Badge/command/application/dto/BadgeAwardDTO.java
  Pick/src/main/java/com/nob/pick/Badge/command/application/service/BadgeService.java
  Pick/src/main/java/com/nob/pick/Badge/command/domain/aggregate/MemberBadge.java
  Pick/src/main/java/com/nob/pick/Badge/command/domain/repository/BadgeRepository.java
  Pick/src/main/java/com/nob/pick/Badge/command/infrastructure/MemberClient.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/controller/MemberAchievementController.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/service/AchievementService.java
  Pick/src/main/java/com/nob/pick/achievement/command/domain/aggregate/MemberAchievement.java
  Pick/src/main/java/com/nob/pick/achievement/command/domain/repository/MemberAchievementRepository.java
  Pick/src/main/java/com/nob/pick/achievement/command/infrastructure/MemberClient.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/controller/MemberDailyMissionController.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/service/MemberDailyMissionService.java
  Pick/src/main/java/com/nob/pick/dailymission/command/domain/aggregate/MemberDailyMission.java
  Pick/src/main/java/com/nob/pick/dailymission/command/infrastructure/MemberClient.java
Labels: 🔧 refactoring

#320 [Refactor] challenge / 뱃지 칼럼명 추가 및 조회 기능 추가
  Pick/src/main/java/com/nob/pick/Badge/command/application/dto/BadgeDTO.java
  Pick/src/main/java/com/nob/pick/Badge/command/application/service/BadgeService.java
  Pick/src/main/java/com/nob/pick/Badge/command/domain/aggregate/Badge.java
  Pick/src/main/java/com/nob/pick/Badge/command/infrastructure/MemberClient.java
  Pick/src/main/java/com/nob/pick/achievement/command/infrastructure/MemberClient.java
  Pick/src/main/java/com/nob/pick/achievement/query/controller/MemberAchievementQueryController.java
  Pick/src/main/java/com/nob/pick/badge/query/controller/BadgeQueryController.java
  Pick/src/main/java/com/nob/pick/badge/query/controller/MemberBadgeQueryController.java
  Pick/src/main/java/com/nob/pick/badge/query/dto/BadgeQueryDTO.java
  Pick/src/main/java/com/nob/pick/badge/query/mapper/BadgeQueryMapper.java
  Pick/src/main/java/com/nob/pick/badge/query/mapper/MemberBadgeQueryMapper.java
  Pick/src/main/java/com/nob/pick/badge/query/service/BadgeQueryService.java
  Pick/src/main/java/com/nob/pick/badge/query/service/BadgeQueryServiceImpl.java
  Pick/src/main/java/com/nob/pick/badge/query/service/MemberBadgeQueryService.java
  Pick/src/main/java/com/nob/pick/badge/query/service/MemberBadgeQueryServiceImpl.java
  Pick/src/main/java/com/nob/pick/common/client/MemberClient.java
  Pick/src/main/java/com/nob/pick/common/dto/MemberResponse.java
  Pick/src/main/java/com/nob/pick/common/util/WebSecurity.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/controller/MemberDailyMissionController.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/service/MemberDailyMissionService.java
  Pick/src/main/java/com/nob/pick/dailymission/query/controller/MemberDailyMissionQueryController.java
  Pick/src/main/resources/com/nob/pick/badge/query/mapper/BadgeQueryMapper.xml
  Pick/src/main/resources/com/nob/pick/badge/query/mapper/MemberBadgeQueryMapper.xml
  Pick/src/test/java/com/nob/pick/badge/BadgeTest.java
  db/challenge/CreateChallengeTable.sql
  db/challenge/InsertDummy.sql
  db/challenge/SelectChallenge.sql
Labels: :sparkles: enhancement, 🔧 refactoring

#327 [Refactor] matching 로직 수정 및 도메인 분리
  Pick/src/main/java/com/nob/pick/common/config/infrastructure/MemberServiceClient.java
  Pick/src/main/java/com/nob/pick/matching/query/controller/MatchingController.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/MatchingInfoDTO.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/SearchMatchingDTO.java
  Pick/src/main/java/com/nob/pick/matching/query/infrastructure/MatchingMemberServiceClient.java
  Pick/src/main/java/com/nob/pick/matching/query/mapper/MatchingMapper.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingService.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingServiceImpl.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/RequestSearchMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/ResponseMemberVO.java
  Pick/src/main/resources/com/nob/pick/matching/query/mapper/MatchingMapper.xml
  db/CreateTotalTables.sql
  db/matching/CreateMatchingTable.sql
  db/matching/MatchingDummyData.sql
Labels: :sparkles: enhancement, 🔧 refactoring

#329 [Style] gitapi 관련 파일들 들여쓰기 수정
  Pick/src/main/java/com/nob/pick/common/util/JwtFilter.java
  Pick/src/main/java/com/nob/pick/common/util/JwtUtil.java
  Pick/src/main/java/com/nob/pick/common/util/WebSecurity.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/controller/GitHubAccountController.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/domain/aggregate/GitHubAccount.java
  Pick/src/main/java/com/nob/pick/gitactivity/query/service/GitHubAccountServiceImpl.java
Labels: :womans_clothes: style

#340 [refactor] 멤버 api에 맞춰 매칭로직 수정
  Pick/src/main/java/com/nob/pick/matching/command/aggregate/MatchingEntity.java
  Pick/src/main/java/com/nob/pick/matching/command/controller/MatchingController.java
  Pick/src/main/java/com/nob/pick/matching/command/dto/CommandMatchingDTO.java
  Pick/src/main/java/com/nob/pick/matching/command/service/MatchingServiceImpl.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/RequestModifyMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/RequestRegistMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/ResponseMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/query/aggregate/Matching.java
  Pick/src/main/java/com/nob/pick/matching/query/controller/MatchingController.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/MatchingDTO.java
  Pick/src/main/java/com/nob/pick/matching/query/infrastructure/MatchingMemberServiceClient.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingServiceImpl.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/ResponseMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/ResponseMemberVO.java
  Pick/src/test/java/com/nob/pick/matching/MatchingTest.java
  README.md
  db/matching/MatchingDummyData.sql
Labels: 🔧 refactoring

#346 [Refactor] dailymission / 일일미션 초기화 기능 추가, 일일미션 부여 기능 및 핸들러 수정
  Pick/src/main/java/com/nob/pick/common/client/MemberClient.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/controller/MemberDailyMissionController.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/infrastructure/MemberClient.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/service/MemberDailyMissionService.java
  Pick/src/main/java/com/nob/pick/dailymission/command/domain/aggregate/MemberDailyMission.java
  Pick/src/main/java/com/nob/pick/dailymission/command/domain/repository/MemberDailyMissionRepository.java
  Pick/src/main/java/com/nob/pick/dailymission/query/dto/MemberDailyMissionQueryDTO.java
  Pick/src/main/resources/com/nob/pick/dailymission/query/mapper/DailyMissionQueryMapper.xml
  Pick/src/main/resources/com/nob/pick/dailymission/query/mapper/MemberDailyMissionQueryMapper.xml
Labels: 🔧 refactoring

#350 [Feature] 깃 커밋, 이슈, PR 조회 기능 구현
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/controller/GitHubAccountController.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/controller/GitHubActivityController.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/CommitDTO.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/IssueDTO.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/LabelDTO.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/PullRequestDTO.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubAccountService.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubAccountServiceImpl.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubActivityService.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubActivityServiceImpl.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/domain/aggregate/GitHubAccount.java
  Pick/src/main/java/com/nob/pick/gitactivity/command/domain/repository/GitHubAccountRepository.java
Labels: :sparkles: enhancement

#360 [Refactor] git / 닫히지 않은 PR과 관련된 브랜치만 조회
  Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubActivityServiceImpl.java
Labels: 🔧 refactoring
