Repository BE14-NoB/Pick, pull requests merged in 2025-03, with the labels that each got.

#6 [Feat] member / 회원 도메인 관련 테이블 DDL
  db/member/CreateTable.sql
Labels: :sparkles: enhancement

#55 [Feat] challenge / 챌린지 도메인 관련 테이블 DDL
  db/challenge/CreateChallengeTable.sql
Labels: :sparkles: enhancement

#17 [Feat] matching / 매칭 도메인 관련 테이블 DDL
  db/matching/CreateMatchingTable.sql
Labels: :sparkles: enhancement

#54 [Feat] post / 게시글 도메인 관련 조회 기능 구현
  db/post/CreateTablePost.sql
  db/post/comment/InsertDummyComment.sql
  db/post/comment/SelectCommentByPostId.sql
  db/post/post/InsertDummyPost.sql
  db/post/post/SelectPost.sql
  db/post/post/SelectPostByTitle.sql
  db/post/post/SelectPostList.sql
  db/post/postImage/InsertDummyPostImage.sql
  db/post/postImage/SelectPostImage.sql
Labels: :sparkles: enhancement

#44 [Feat] post / 게시글 도메인 관련 테이블 DDL
  db/post/CreateTablePost.sql
Labels: :sparkles: enhancement

#57 [Docs] git / 리팩토링, 스타일 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/issue_template_refactoring.yaml
  .github/ISSUE_TEMPLATE/issue_template_style.yaml
Labels: :page_facing_up: documentation

#56 [REFACTOR] member / 회원 도메인 관련 테이블 DDL 수정
  db/member/CreateMemberTable.sql
  db/member/CreateTable.sql
Labels: 🔧 refactoring

#58 [Refactor] report / 컨벤션에 맞게 코드 수정 및 변수 타입 수정
  db/report/CreateReportTable.sql
Labels: 🔧 refactoring, :womans_clothes: style

#62 [Docs] git / 스타일 이슈 템플릿 수정 및 문서 템플릿 생성
  .github/ISSUE_TEMPLATE/issue_template_documentation.yaml
  .github/ISSUE_TEMPLATE/issue_template_style.yaml
Labels: :page_facing_up: documentation

#66 [Refactor] matching / 매칭 도메인 관련 테이블 DDL 구문 수정
  db/matching/CreateMatchingTable.sql
Labels: 🔧 refactoring, :womans_clothes: style

#70 [Refactor] challenge / 챌린지 도메인 관련 테이블 제약조건 수정, 컬럼명 삭제 및 수정
  db/challenge/CreateChallengeTable.sql
Labels: 🔧 refactoring

#72 [RENAME] 패키지 폴더 초안 작성
  Pick/src/main/java/com/nob/pick/challenge/intro
  Pick/src/main/java/com/nob/pick/common/config/intro
  Pick/src/main/java/com/nob/pick/common/exception/intro
  Pick/src/main/java/com/nob/pick/matching/intro
  Pick/src/main/java/com/nob/pick/member/command/application/intro
  Pick/src/main/java/com/nob/pick/member/command/controller/intro
  Pick/src/main/java/com/nob/pick/member/command/domain/intro
  Pick/src/main/java/com/nob/pick/member/command/infrastructure/intro
  Pick/src/main/java/com/nob/pick/member/query/application/intro
  Pick/src/main/java/com/nob/pick/member/query/controller/intro
  Pick/src/main/java/com/nob/pick/member/query/infrastructure/intro
  Pick/src/main/java/com/nob/pick/post/intro
  Pick/src/main/java/com/nob/pick/project/intro
  Pick/src/main/java/com/nob/pick/report/intro
Labels: :sparkles: enhancement

#73 [Refactor] project / 프로젝트 도메인 관련 테이블 DDL 구문 수정
  db/project/CreateProjectTable.sql
  db/project/DummyProject.sql
  db/project/ProjectDummyData.sql
  db/project/SelectProjectTable.sql
Labels: 🔧 refactoring

#84 [Chore] challenge / 챌린지 관련 테이블 더미 데이터 생성
  db/challenge/InsertDummy.sql
Labels: :test_tube: test

#76 [Refactor] post / ENUM -> TINYINT로 수정, PK, FK, CONSTRAINT 이름 지정
  db/post/CreateTablePost.sql
Labels: 🔧 refactoring

#78 [Refactor] challenge / 뱃지 테이블에 가산점 컬럼 추가
  db/challenge/CreateChallengeTable.sql
Labels: 🔧 refactoring

#87 [Refactor] post / 테이블 컬럼명 변경에 따른 기존 INSERT, SELECT문 변경
  db/post/comment/InsertDummyComment.sql
  db/post/comment/SelectCommentByPostId.sql
  db/post/post/InsertDummyPost.sql
  db/post/post/SelectPost.sql
  db/post/post/SelectPostByTitle.sql
  db/post/post/SelectPostList.sql
  db/post/postImage/InsertDummyPostImage.sql
  db/post/postImage/SelectPostImage.sql
Labels: 🔧 refactoring

#95 [Feat] challenge/ 챌린지 도메인 관련 조회 기능 구현
  db/challenge/SelectChallenge.sql
Labels: :sparkles: enhancement

#91 [Refactor] report / 신고 관련 테이블 더미 데이터 수정
  db/report/ReportDummyData.sql
Labels: 🔧 refactoring

#101 [Feat] project / 프로젝트 도메인 관련 조회 기능 구현
  db/project/CreateProjectTable.sql
  db/project/InsertDummyAllProject.sql
  db/project/memberReview/InsertDummyMemberReview.sql
  db/project/memberReview/SelectMemberReviewByMemberId.sql
  db/project/participant/InsertDummyParticipant.sql
  db/project/participant/SelectParticipantByProjectId.sql
  db/project/projectMeeting/InsertDummyProjectMeeting.sql
  db/project/projectMeeting/SelectProjectMeetingByProjectId.sql
  db/project/projectMeeting/SelectProjectMeetingImages.sql
  db/project/projectReview/InsertDummyProjectReview.sql
  db/project/projectReview/SelectProjectReviewByProjectId.sql
  db/project/projectRoom/InsertDummyProjectRoom.sql
  db/project/projectRoom/SelectActiveProject.sql
  db/project/projectRoom/SelectDeletedProject.sql
  db/project/projectRoom/SelectFinishedProject.sql
  db/project/projectRoom/SelectMatchingProject.sql
  db/project/projectRoom/SelectProjectByKeyword.sql
Labels: :sparkles: enhancement

#108 [Chore] matching / 매칭 관련 테이블 더미 데이터 생성
  db/matching/MatchingDummyData.sql
Labels: :test_tube: test

#104 [Feat] member/ 회원 테이블 관련 select문 기능 구현
  db/member/CreateDummyData.sql
  db/member/SelectAllMembers.sql
  db/member/SelectEmailByNameAndPhone.sql
  db/member/SelectExistsByEmail.sql
  db/member/SelectExistsByPhoneNumber.sql
  db/member/SelectExpAndLevelByMeberId.sql
  db/member/SelectImagePathByMemberId.sql
  db/member/SelectMemberById.sql
  db/member/SelectMemberLanguageByMemberId.sql
  db/member/SelectMemberProfliePageByMemberId.sql
  db/member/SelectMemberStatus.sql
  db/member/SelectPasswordByNamePhoneAndEmail.sql
  db/member/SelectProgrammingLanguage.sql
Labels: :sparkles: enhancement

#110 [Refactor] challenge/ 챌린지 도메인 관련 테이블 DDL 수정
  db/challenge/CreateChallengeTable.sql
Labels: 🔧 refactoring

#114 [Comment] post / status 컬럼에 주석 추가
  db/post/CreateTablePost.sql
Labels: 🎨 design

#116 [Chore] post / 더미 데이터 추가 및 형식 일부 수정
  db/post/CreateTablePost.sql
  db/post/comment/InsertDummyComment.sql
  db/post/post/InsertDummyPost.sql
  db/post/postImage/InsertDummyPostImage.sql
Labels: :test_tube: test

#132 [Feat] report / 신고 목록 조회 구현
  Pick/src/main/java/com/nob/pick/common/config/typehandler/ReportCategoryEnumTypeHandler.java
  Pick/src/main/java/com/nob/pick/common/config/typehandler/ReportStatusEnumTypeHandler.java
  Pick/src/main/java/com/nob/pick/common/config/typehandler/StringYnTypeHandler.java
  Pick/src/main/java/com/nob/pick/report/query/controller/ReportController.java
  Pick/src/main/java/com/nob/pick/report/query/dao/ReportMapper.java
  Pick/src/main/java/com/nob/pick/report/query/dto/ReportDTO.java
  Pick/src/main/java/com/nob/pick/report/query/dto/ReportReasonDTO.java
  Pick/src/main/java/com/nob/pick/report/query/dto/enums/ReportCategory.java
  Pick/src/main/java/com/nob/pick/report/query/dto/enums/ReportStatus.java
  Pick/src/main/java/com/nob/pick/report/query/service/ReportService.java
  Pick/src/main/java/com/nob/pick/report/query/service/ReportServiceImpl.java
  Pick/src/main/resources/application.properties
  Pick/src/main/resources/com/nob/pick/report/query/dao/ReportMapper.xml
  Pick/src/main/resources/mybatis-config.xml
  db/report/CreateReportTable.sql
  db/report/SelectReport.sql
Labels: :sparkles: enhancement

#162 [Feat] matching / 매칭 관련 도메인 조회 구현
  Pick/src/main/java/com/nob/pick/common/config/typehandler/DateTimeTypeHandler.java
  Pick/src/main/java/com/nob/pick/matching/query/aggregate/Matching.java
  Pick/src/main/java/com/nob/pick/matching/query/aggregate/MatchingEntry.java
  Pick/src/main/java/com/nob/pick/matching/query/aggregate/TechnologyCategory.java
  Pick/src/main/java/com/nob/pick/matching/query/controller/MatchingController.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/MatchingDTO.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/MatchingEntryDTO.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/TechnologyCategoryDTO.java
  Pick/src/main/java/com/nob/pick/matching/query/mapper/MatchingMapper.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingService.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingServiceImpl.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/ResponseMatchingEntryVO.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/ResponseMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/ResponseTechnologyCategoryVO.java
  Pick/src/main/resources/com/nob/pick/matching/query/mapper/MatchingMapper.xml
  Pick/src/main/resources/mybatis-config.xml
  db/matching/CreateMatchingTable.sql
  db/matching/MatchingDummyData.sql
Labels: :sparkles: enhancement

#178 [Refactor] challenge/ 챌린지 관련 도메인 handler 위치 수정
  Pick/src/main/resources/com/nob/pick/achievement/query/mapper/AchievementQueryMapper.xml
  Pick/src/main/resources/com/nob/pick/badge/query/mapper/BadgeQueryMapper.xml
  Pick/src/main/resources/com/nob/pick/dailymission/query/mapper/DailyMissionQueryMapper.xml
  Pick/src/main/resources/com/nob/pick/dailymission/query/mapper/MemberDailyMissionQueryMapper.xml
Labels: :bug: bug

#167 [Feat] post / 게시글 도메인 관련 조회 기능 구현
  Pick/src/main/java/com/nob/pick/common/config/MybatisConfiguration.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/CommentDTO.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/MemberNicknameDTO.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/PostCommentDTO.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/PostDTO.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/PostImageDTO.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/PostListDTO.java
  Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/entity/Post.java
  Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponseCommentVO.java
  Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponsePostCommentVO.java
  Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponsePostImageVO.java
  Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponsePostListVO.java
  Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponsePostVO.java
  Pick/src/main/java/com/nob/pick/post/query/controller/PostController.java
  Pick/src/main/java/com/nob/pick/post/query/mapper/PostMapper.java
  Pick/src/main/java/com/nob/pick/post/query/service/PostService.java
  Pick/src/main/java/com/nob/pick/post/query/service/PostServiceImpl.java
  Pick/src/main/resources/com/nob/pick/post/query/mapper/PostMapper.xml
Labels: :sparkles: enhancement

#173 [Feat] report / 신고 도메인 관련 등록, 삭제, 수정 기능 구현
  Pick/src/main/java/com/nob/pick/report/command/application/controller/ReportController.java
  Pick/src/main/java/com/nob/pick/report/command/application/dto/ReportCategory.java
  Pick/src/main/java/com/nob/pick/report/command/application/dto/ReportDTO.java
  Pick/src/main/java/com/nob/pick/report/command/application/dto/ReportReasonDTO.java
  Pick/src/main/java/com/nob/pick/report/command/application/dto/ReportStatus.java
  Pick/src/main/java/com/nob/pick/report/command/application/service/ReportReasonService.java
  Pick/src/main/java/com/nob/pick/report/command/application/service/ReportReasonServiceImpl.java
  Pick/src/main/java/com/nob/pick/report/command/application/service/ReportService.java
  Pick/src/main/java/com/nob/pick/report/command/application/service/ReportServiceImpl.java
  Pick/src/main/java/com/nob/pick/report/command/domain/aggregate/Report.java
  Pick/src/main/java/com/nob/pick/report/command/domain/aggregate/ReportReason.java
  Pick/src/main/java/com/nob/pick/report/command/domain/repository/ReportReasonRepository.java
  Pick/src/main/java/com/nob/pick/report/command/domain/repository/ReportRepository.java
  Pick/src/main/java/com/nob/pick/report/command/domain/service/ReportService.java
  Pick/src/main/java/com/nob/pick/report/command/domain/service/ReportServiceImpl.java
  Pick/src/main/java/com/nob/pick/report/query/controller/ReportController.java
  Pick/src/main/java/com/nob/pick/report/query/dto/ReportDTO.java
  Pick/src/main/java/com/nob/pick/report/query/dto/ReportReasonDTO.java
  Pick/src/main/java/com/nob/pick/report/query/service/ReportService.java
  Pick/src/main/java/com/nob/pick/report/query/service/ReportServiceImpl.java
Labels: :sparkles: enhancement

#175 [Feature] project 프로젝트 도메인 관련 조회 기능 구현
  Pick/src/main/java/com/nob/pick/common/config/MybatisConfiguration.java
  Pick/src/main/java/com/nob/pick/common/config/typehandler/StatusEnumTypeHandler.java
  Pick/src/main/java/com/nob/pick/common/config/typehandler/UserGrantEnumTypeHandler.java
  Pick/src/main/java/com/nob/pick/matching/query/aggregate/TechnologyCategory.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/MemberReview.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/Participant.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/ProjectMeeting.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/ProjectMeetingImage.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/ProjectReview.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/ProjectRoom.java
  Pick/src/main/java/com/nob/pick/project/query/aggregate/MemberReview.java
  Pick/src/main/java/com/nob/pick/project/query/aggregate/ProjectMeeting.java
  Pick/src/main/java/com/nob/pick/project/query/aggregate/ProjectMeetingImage.java
  Pick/src/main/java/com/nob/pick/project/query/aggregate/ProjectReview.java
  Pick/src/main/java/com/nob/pick/project/query/aggregate/ProjectRoom.java
  Pick/src/main/java/com/nob/pick/project/query/controller/MeetingController.java
  Pick/src/main/java/com/nob/pick/project/query/controller/ProjectRoomController.java
  Pick/src/main/java/com/nob/pick/project/query/controller/ReviewController.java
  Pick/src/main/java/com/nob/pick/project/query/dto/MeetingDTO.java
  Pick/src/main/java/com/nob/pick/project/query/dto/MemberReviewDTO.java
  Pick/src/main/java/com/nob/pick/project/query/dto/ParticipantDTO.java
  Pick/src/main/java/com/nob/pick/project/query/dto/ProjectReviewDTO.java
  Pick/src/main/java/com/nob/pick/project/query/dto/ProjectRoomDTO.java
  Pick/src/main/java/com/nob/pick/project/query/mapper/ParticipantMapper.java
  Pick/src/main/java/com/nob/pick/project/query/mapper/ProjectMeetingMapper.java
  Pick/src/main/java/com/nob/pick/project/query/mapper/ProjectRoomMapper.java
  Pick/src/main/java/com/nob/pick/project/query/mapper/ReviewMapper.java
  Pick/src/main/java/com/nob/pick/project/query/service/MeetingService.java
  Pick/src/main/java/com/nob/pick/project/query/service/MeetingServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/query/service/ParticipantService.java
  Pick/src/main/java/com/nob/pick/project/query/service/ParticipantServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/query/service/ProjectRoomService.java
  Pick/src/main/java/com/nob/pick/project/query/service/ProjectRoomServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/query/service/ReviewService.java
  Pick/src/main/java/com/nob/pick/project/query/service/ReviewServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ReponseMeetingVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ReponseParticipantReviewVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/RequestEnterProject.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseActiveProjectRoomVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseEnterProject.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseFinishedProjectDetailVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseMeetingVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseParticipantVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseProjectReviewVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseProjectVO.java
  Pick/src/main/resources/com/nob/pick/member/query/mapper/MemberMapper.xml
  Pick/src/main/resources/com/nob/pick/project/query/mapper/ParticipantMapper.xml
  Pick/src/main/resources/com/nob/pick/project/query/mapper/ProjectMeetingMapper.xml
  Pick/src/main/resources/com/nob/pick/project/query/mapper/ProjectRoomMapper.xml
  Pick/src/main/resources/com/nob/pick/project/query/mapper/ReviewMapper.xml
  Pick/src/test/java/com/nob/pick/project/ProjectRoomTest.java
  db/project/CreateProjectTable.sql
  db/project/InsertDummyAllProject.sql
  db/project/SelectProjectTable.sql
  db/project/memberReview/SelectMemberReviewByMemberId.sql
  db/project/participant/SelectParticipantByProjectId.sql
  db/project/projectMeeting/InsertDummyProjectMeeting.sql
  db/project/projectMeeting/SelectProjectMeetingByProjectId.sql
  db/project/projectMeeting/SelectProjectMeetingImages.sql
  db/project/projectReview/SelectProjectReviewByProjectId.sql
Labels: :sparkles: enhancement

#181 [Refactor] badge / 회원별 획득 뱃지 경로 수정
  Pick/src/main/java/com/nob/pick/badge/query/controller/MemberBadgeQueryController.java
Labels: 🔧 refactoring

#191 [Feat] post / 게시글 등록, 삭제 기능 구현 + [Fix] post / 단일 게시글 조회 수정
  Pick/src/main/java/com/nob/pick/common/config/typehandler/PostCategoryEnumTypeHandler.java
  Pick/src/main/java/com/nob/pick/common/config/typehandler/PostStatusEnumTypeHandler.java
  Pick/src/main/java/com/nob/pick/post/command/application/controller/CommandPostController.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/CommentDTO.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/PostCategory.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/PostCommentDTO.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/PostDTO.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/PostListDTO.java
  Pick/src/main/java/com/nob/pick/post/command/application/dto/PostStatus.java
  Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostService.java
  Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostServiceImpl.java
  Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/entity/Post.java
  Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponseCommentVO.java
  Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponseRegisterPostVO.java
  Pick/src/main/java/com/nob/pick/post/command/domain/repository/PostRepository.java
  Pick/src/main/java/com/nob/pick/post/query/controller/PostController.java
  Pick/src/main/java/com/nob/pick/post/query/mapper/PostMapper.java
  Pick/src/main/java/com/nob/pick/post/query/service/PostService.java
  Pick/src/main/java/com/nob/pick/post/query/service/PostServiceImpl.java
  Pick/src/main/resources/com/nob/pick/post/query/mapper/PostMapper.xml
Labels: :bug: bug, :sparkles: enhancement, 🔧 refactoring

#193 [Feat] report / Report 도메인 관련 조회 기능 추가 구현
  Pick/src/main/java/com/nob/pick/report/query/controller/ReportController.java
  Pick/src/main/java/com/nob/pick/report/query/dao/ReportMapper.java
  Pick/src/main/java/com/nob/pick/report/query/service/ReportService.java
  Pick/src/main/java/com/nob/pick/report/query/service/ReportServiceImpl.java
  Pick/src/main/resources/com/nob/pick/report/query/dao/ReportMapper.xml
Labels: :sparkles: enhancement

#195 [Feat] regulation / Regulation 도메인 관련 조회 구현
  Pick/src/main/java/com/nob/pick/regulation/query/controller/RegulationController.java
  Pick/src/main/java/com/nob/pick/regulation/query/dao/RegulationMapper.java
  Pick/src/main/java/com/nob/pick/regulation/query/dto/RegulationDTO.java
  Pick/src/main/java/com/nob/pick/regulation/query/service/RegulationService.java
  Pick/src/main/java/com/nob/pick/regulation/query/service/RegulationServiceImpl.java
  Pick/src/main/resources/com/nob/pick/regulation/query/dao/RegulationMapper.xml
Labels: :sparkles: enhancement

#198 [Feat] regulation / Regulation 등록, 삭제 기능 구현
  Pick/src/main/java/com/nob/pick/regulation/command/application/controller/RegulationController.java
  Pick/src/main/java/com/nob/pick/regulation/command/application/dto/RegulationDTO.java
  Pick/src/main/java/com/nob/pick/regulation/command/application/service/RegulationImpl.java
  Pick/src/main/java/com/nob/pick/regulation/command/application/service/RegulationService.java
  Pick/src/main/java/com/nob/pick/regulation/command/domain/aggregate/Regulation.java
  Pick/src/main/java/com/nob/pick/regulation/command/domain/repository/RegulationRepository.java
Labels: :sparkles: enhancement

#211 [Feat] Member, Security / Member도메인 Command 및 Security 구현
  Pick/build.gradle
  Pick/src/main/java/com/nob/pick/common/config/PasswordConfig.java
  Pick/src/main/java/com/nob/pick/common/util/JwtAuthenticationProvider.java
  Pick/src/main/java/com/nob/pick/common/util/JwtFilter.java
  Pick/src/main/java/com/nob/pick/common/util/JwtUtil.java
  Pick/src/main/java/com/nob/pick/common/util/TokenBlacklist.java
  Pick/src/main/java/com/nob/pick/common/util/WebSecurity.java
  Pick/src/main/java/com/nob/pick/member/command/controller/MemberCommandController.java
  Pick/src/main/java/com/nob/pick/member/command/dto/AddMemberLanguageDTO.java
  Pick/src/main/java/com/nob/pick/member/command/dto/AddProgrammingLanguageDTO.java
  Pick/src/main/java/com/nob/pick/member/command/dto/LoginDTO.java
  Pick/src/main/java/com/nob/pick/member/command/dto/SignUpCommandDTO.java
  Pick/src/main/java/com/nob/pick/member/command/dto/UpdateMemberCommandDTO.java
  Pick/src/main/java/com/nob/pick/member/command/dto/UpdateMemberLanguageDTO.java
  Pick/src/main/java/com/nob/pick/member/command/dto/UpdateMemberProfilePageCommandDTO.java
  Pick/src/main/java/com/nob/pick/member/command/dto/UpdateProfileStatusDTO.java
  Pick/src/main/java/com/nob/pick/member/command/dto/UpdateProgrammingLanguageDTO.java
  Pick/src/main/java/com/nob/pick/member/command/dto/UpdateStatusCommandDTO.java
  Pick/src/main/java/com/nob/pick/member/command/entity/Member.java
  Pick/src/main/java/com/nob/pick/member/command/entity/MemberProfilePage.java
  Pick/src/main/java/com/nob/pick/member/command/entity/MemberProgrammingLanguage.java
  Pick/src/main/java/com/nob/pick/member/command/entity/ProgrammingLanguage.java
  Pick/src/main/java/com/nob/pick/member/command/repository/MemberProfilePageRepository.java
  Pick/src/main/java/com/nob/pick/member/command/repository/MemberProgrammingLanguageRepository.java
  Pick/src/main/java/com/nob/pick/member/command/repository/ProgrammingLanguageRepository.java
  Pick/src/main/java/com/nob/pick/member/command/service/MemberCommandService.java
  Pick/src/main/java/com/nob/pick/member/command/vo/UpdateMemberStatusVO.java
  Pick/src/main/java/com/nob/pick/member/query/controller/MemberController.java
  Pick/src/main/java/com/nob/pick/member/query/dto/EmailCheckRequestDTO.java
  Pick/src/main/java/com/nob/pick/member/query/dto/EmailCheckResponseDTO.java
  Pick/src/main/java/com/nob/pick/member/query/dto/PhoneCheckRequestDTO.java
  Pick/src/main/java/com/nob/pick/member/query/dto/PhoneCheckResponseDTO.java
  Pick/src/main/java/com/nob/pick/member/query/mapper/MemberMapper.java
  Pick/src/main/java/com/nob/pick/member/query/service/MemberService.java
  Pick/src/main/resources/com/nob/pick/member/query/mapper/MemberMapper.xml
  Pick/src/test/java/com/nob/pick/member/command/controller/MemberCommandControllerTest.java
Labels: :sparkles: enhancement

#212 [Feat] challenge/dailymission/achievement/badge 도메인 Command 구현
  Pick/src/main/java/com/nob/pick/Badge/command/application/controller/BadgeController.java
  Pick/src/main/java/com/nob/pick/Badge/command/application/dto/BadgeAwardDTO.java
  Pick/src/main/java/com/nob/pick/Badge/command/application/dto/BadgeDTO.java
  Pick/src/main/java/com/nob/pick/Badge/command/application/service/BadgeService.java
  Pick/src/main/java/com/nob/pick/Badge/command/domain/aggregate/Badge.java
  Pick/src/main/java/com/nob/pick/Badge/command/domain/aggregate/MemberBadge.java
  Pick/src/main/java/com/nob/pick/Badge/command/domain/repository/BadgeRepository.java
  Pick/src/main/java/com/nob/pick/Badge/command/domain/repository/MemberBadgeRepository.java
  Pick/src/main/java/com/nob/pick/PickApplication.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/controller/AchievementController.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/controller/MemberAchievementController.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/dto/AchievementCreateRequestDTO.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/dto/AchievementResponseDTO.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/dto/AchievementUpdateRequestDTO.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/dto/MemberAchievementDTO.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/dto/ProgressUpdateRequestDTO.java
  Pick/src/main/java/com/nob/pick/achievement/command/application/service/AchievementService.java
  Pick/src/main/java/com/nob/pick/achievement/command/domain/aggregate/Achievement.java
  Pick/src/main/java/com/nob/pick/achievement/command/domain/aggregate/MemberAchievement.java
  Pick/src/main/java/com/nob/pick/achievement/command/domain/repository/AchievementRepository.java
  Pick/src/main/java/com/nob/pick/achievement/command/domain/repository/MemberAchievementRepository.java
  Pick/src/main/java/com/nob/pick/challenge/command/application/controller/ChallengeController.java
  Pick/src/main/java/com/nob/pick/challenge/command/application/dto/ChallengeRequestDTO.java
  Pick/src/main/java/com/nob/pick/challenge/command/application/dto/ChallengeResponseDTO.java
  Pick/src/main/java/com/nob/pick/challenge/command/application/service/ChallengeService.java
  Pick/src/main/java/com/nob/pick/challenge/command/domain/aggregate/Challenge.java
  Pick/src/main/java/com/nob/pick/challenge/command/domain/repository/ChallengeRepository.java
  Pick/src/main/java/com/nob/pick/common/config/BooleanToYNConverter.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/controller/DailyMissionAssignmentController.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/controller/DailyMissionController.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/dto/DailyMissionRequest.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/service/DailyMissionAssignmentService.java
  Pick/src/main/java/com/nob/pick/dailymission/command/application/service/DailyMissionService.java
  Pick/src/main/java/com/nob/pick/dailymission/command/domain/aggregate/DailyMission.java
  Pick/src/main/java/com/nob/pick/dailymission/command/domain/aggregate/MemberDailyMission.java
  Pick/src/main/java/com/nob/pick/dailymission/command/domain/repository/DailyMissionRepository.java
  Pick/src/main/java/com/nob/pick/dailymission/command/domain/repository/MemberDailyMissionRepository.java
  db/challenge/CreateChallengeTable.sql
Labels: :sparkles: enhancement

#216 [Feat] project / 프로젝트 도메인 관련 CREATE 기능 구현
  Pick/src/main/java/com/nob/pick/common/config/convertor/BooleanToYNConverter.java
  Pick/src/main/java/com/nob/pick/project/command/application/controller/MeetingController.java
  Pick/src/main/java/com/nob/pick/project/command/application/controller/ProjectRoomController.java
  Pick/src/main/java/com/nob/pick/project/command/application/controller/ReviewController.java
  Pick/src/main/java/com/nob/pick/project/command/application/dto/MemberReviewDTO.java
  Pick/src/main/java/com/nob/pick/project/command/application/dto/ParticipantDTO.java
  Pick/src/main/java/com/nob/pick/project/command/application/dto/ProjectReviewDTO.java
  Pick/src/main/java/com/nob/pick/project/command/application/dto/ProjectRoomDTO.java
  Pick/src/main/java/com/nob/pick/project/command/application/dto/RequestParticipantDTO.java
  Pick/src/main/java/com/nob/pick/project/command/application/dto/RequestProjectRoomDTO.java
  Pick/src/main/java/com/nob/pick/project/command/application/service/MeetingService.java
  Pick/src/main/java/com/nob/pick/project/command/application/service/MeetingServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/command/application/service/ProjectRoomService.java
  Pick/src/main/java/com/nob/pick/project/command/application/service/ProjectRoomServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/command/application/service/ReviewService.java
  Pick/src/main/java/com/nob/pick/project/command/application/service/ReviewServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/MemberReview.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/Participant.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/ProjectMeeting.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/ProjectMeetingImage.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/ProjectRoom.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/entity/MemberReview.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/entity/Participant.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/entity/ProjectMeeting.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/entity/ProjectMeetingImage.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/entity/ProjectReview.java
  Pick/src/main/java/com/nob/pick/project/command/domain/aggregate/entity/ProjectRoom.java
  Pick/src/main/java/com/nob/pick/project/command/domain/repository/MeetingRepository.java
  Pick/src/main/java/com/nob/pick/project/command/domain/repository/MemberReviewRepository.java
  Pick/src/main/java/com/nob/pick/project/command/domain/repository/ParticipantRepository.java
  Pick/src/main/java/com/nob/pick/project/command/domain/repository/ProjectReviewRepository.java
  Pick/src/main/java/com/nob/pick/project/command/domain/repository/ProjectRoomRepository.java
  Pick/src/main/java/com/nob/pick/project/query/aggregate/ProjectMeeting.java
  Pick/src/main/java/com/nob/pick/project/query/aggregate/ProjectRoom.java
  Pick/src/main/java/com/nob/pick/project/query/controller/MeetingController.java
  Pick/src/main/java/com/nob/pick/project/query/controller/ProjectRoomController.java
  Pick/src/main/java/com/nob/pick/project/query/controller/ReviewController.java
  Pick/src/main/java/com/nob/pick/project/query/dto/MeetingDTO.java
  Pick/src/main/java/com/nob/pick/project/query/dto/MemberReviewDTO.java
  Pick/src/main/java/com/nob/pick/project/query/service/MeetingServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/query/service/ParticipantServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/query/service/ProjectRoomService.java
  Pick/src/main/java/com/nob/pick/project/query/service/ProjectRoomServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/query/service/ReviewServiceImpl.java
  Pick/src/main/resources/com/nob/pick/project/query/mapper/ParticipantMapper.xml
  Pick/src/main/resources/com/nob/pick/project/query/mapper/ReviewMapper.xml
  Pick/src/test/java/com/nob/pick/project/ProjectRoomTest.java
Labels: :sparkles: enhancement, 🔧 refactoring

#222 hotfix : eureka 관련 및 Security 설정 수정
  Pick/build.gradle
  Pick/src/main/java/com/nob/pick/PickApplication.java
  Pick/src/main/java/com/nob/pick/common/config/SecurityConfig.java
  Pick/src/main/java/com/nob/pick/common/util/WebSecurity.java
  Pick/src/main/resources/com/nob/pick/member/query/mapper/MemberMapper.xml
Labels: 🚨 HOTFIX

#218 [Refactor] post / CommandPostController 일부 수정
  Pick/src/main/java/com/nob/pick/post/command/application/controller/CommandPostController.java
Labels: 🔧 refactoring

#223 Feat: matching 도메인 관련 수동 merge
  Pick/src/main/java/com/nob/pick/matching/command/aggregate/MatchingEntity.java
  Pick/src/main/java/com/nob/pick/matching/command/aggregate/MatchingEntryEntity.java
  Pick/src/main/java/com/nob/pick/matching/command/aggregate/TechnologyCategoryEntity.java
  Pick/src/main/java/com/nob/pick/matching/command/controller/MatchingController.java
  Pick/src/main/java/com/nob/pick/matching/command/dto/CommandMatchingDTO.java
  Pick/src/main/java/com/nob/pick/matching/command/dto/CommandMatchingEntryDTO.java
  Pick/src/main/java/com/nob/pick/matching/command/dto/CommandTechnologyCategoryDTO.java
  Pick/src/main/java/com/nob/pick/matching/command/repository/MatchingEntryRepository.java
  Pick/src/main/java/com/nob/pick/matching/command/repository/MatchingRepository.java
  Pick/src/main/java/com/nob/pick/matching/command/repository/TechnologyCategoryRepository.java
  Pick/src/main/java/com/nob/pick/matching/command/service/MatchingService.java
  Pick/src/main/java/com/nob/pick/matching/command/service/MatchingServiceImpl.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/RequestModifyMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/RequestModifyTechnologyCategoryVO.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/RequestRegistMatchingEntryVO.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/RequestRegistMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/RequestRegistTechnologyCategoryVO.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/ResponseMatchingEntryVO.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/ResponseMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/command/vo/ResponseTechnologyCategoryVO.java
  Pick/src/main/java/com/nob/pick/matching/query/aggregate/Matching.java
  Pick/src/main/java/com/nob/pick/matching/query/aggregate/MatchingEntry.java
  Pick/src/main/java/com/nob/pick/matching/query/controller/MatchingController.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/MatchingDTO.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/MatchingInfo.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/MatchingInfoDTO.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/SearchMatchingDTO.java
  Pick/src/main/java/com/nob/pick/matching/query/mapper/MatchingMapper.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingService.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingServiceImpl.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/RequestSearchMatchingVO.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/ResponseMatchingVO.java
  Pick/src/main/resources/com/nob/pick/matching/query/mapper/MatchingMapper.xml
Labels: :sparkles: enhancement

#224 hotfix: 타입 핸들러 확장자 추가
  Pick/src/main/java/com/nob/pick/common/config/typehandler/LocalDateTimeTypeHandler.java
  Pick/src/main/java/com/nob/pick/common/config/typehandler/LocalDateTypeHandler.java
Labels: 🚨 HOTFIX

#227 refactor : xml파일 누락 수정
  kick-member/src/main/resources/com/nob/kickmember/member/query/mapper/MemberMapper.xml
Labels: 🔧 refactoring

#234 document : postman api결과를 위한 폴더 생성
  postman/member/intro.txt
Labels: :page_facing_up: documentation

#232 [Readme] 프로젝트 관련 API TEST 캡쳐본
  README.md
Labels: :page_facing_up: documentation

#237 [Feat] server / config 서버 업로드
  Pick/build.gradle
  Pick/src/main/java/com/nob/pick/PickApplication.java
  Pick/src/main/java/com/nob/pick/common/util/WebSecurity.java
  Pick/src/main/resources/bootstrap.yml
  kick-member/build.gradle
  kick-member/src/main/java/com/nob/kickmember/KickMemberApplication.java
  kick-member/src/main/java/com/nob/kickmember/common/util/WebSecurity.java
  kick-member/src/main/resources/bootstrap.yml
  kick-member/src/main/resources/com/nob/kickmember/member/query/mapper/MemberMapper.xml
  pick-config-server/.gitattributes
  pick-config-server/.gitignore
  pick-config-server/build.gradle
  pick-config-server/gradle/wrapper/gradle-wrapper.jar
  pick-config-server/gradle/wrapper/gradle-wrapper.properties
  pick-config-server/gradlew
  pick-config-server/gradlew.bat
  pick-config-server/settings.gradle
  pick-config-server/src/main/java/com/nob/pick/pickconfigserver/PickConfigServerApplication.java
  pick-config-server/src/test/java/com/nob/pick/pickconfigserver/PickConfigServerApplicationTests.java
  pick-gateway/build.gradle
  pick-gateway/src/main/java/com/nob/pick/pickgateway/filter/AuthorizationHeaderFilter.java
  pick-gateway/src/main/resources/bootstrap.yml
Labels: :bug: bug, :sparkles: enhancement, 🚨 HOTFIX

#235 doc : postman 회원 도메인 결과 추가
  postman/member/fail/멤버 전체 조회 (실패 401).png
  postman/member/fail/이메일 중복 검사(실패 409 중복).png
  postman/member/fail/인회원 로그인 (실패 401).png
  postman/member/fail/전화번호 중복 검사 (실패 409 중복).png
  postman/member/fail/회원 가입 (실패 이메일 중복 401).png
  postman/member/success/로그아웃 (성공).png
  postman/member/success/로그인(성공).png
  postman/member/success/멤버 전체 조회 (성공).png
  postman/member/success/비밀번호 찾기 (성공).png
  postman/member/success/이메일 조회 (성공).png
  postman/member/success/이메일 중복 검사 (성공).png
  postman/member/success/전화번호 중복 검사 (성공).png
  postman/member/success/특정 회원 조회 (성공).png
  postman/member/success/특정 회원 프로필 조회 (성공).png
  postman/member/success/프로필 정보 수정 (성공).png
  postman/member/success/회원 가입 (성공).png
  postman/member/success/회원 권한 조회 (성공).png
  postman/member/success/회원 상태 조회 (성공).png
  postman/member/success/회원 정보 수정 (성공).png
Labels: :page_facing_up: documentation

#239 [Matching] Test 코드 작성 및 코드 리팩토링
  Pick/src/main/java/com/nob/pick/matching/command/controller/MatchingController.java
  Pick/src/main/java/com/nob/pick/matching/command/service/MatchingServiceImpl.java
  Pick/src/main/java/com/nob/pick/matching/query/controller/MatchingController.java
  Pick/src/main/java/com/nob/pick/matching/query/dto/MatchingInfo.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingService.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingServiceImpl.java
  Pick/src/test/java/com/nob/pick/matching/MatchingTest.java
  db/matching/CreateMatchingTable.sql
  db/matching/MatchingDummyData.sql
  postman/matching/기술 카테고리 id로 조회.png
  postman/matching/기술 카테고리 id로 하위 카테고리 조회.png
  postman/matching/기술 카테고리 등록.png
  postman/matching/기술 카테고리 삭제.png
  postman/matching/기술 카테고리 수정.png
  postman/matching/기술 카테고리 전체 조회.png
  postman/matching/기술 카테고리 조건 매칭.png
  postman/matching/매칭 조회.png
  postman/matching/매칭방 id로 신청자 조회.png
  postman/matching/매칭방 id로 조회.png
  postman/matching/매칭방 등록.png
  postman/matching/매칭방 삭제.png
  postman/matching/매칭방 수정.png
  postman/matching/매칭방 신청 취소.png
  postman/matching/매칭방 신청.png
  postman/matching/매칭방 전체 조회.png
  postman/matching/상위 기술 카테고리만 조회.png
  postman/matching/수락한 신청자만 조회.png
  postman/matching/신청자 수락.png
  postman/matching/카테고리 id로 매칭방 조회.png
Labels: 🔧 refactoring, :test_tube: test

#251 [test] challenge / 테스트 코드 작성 및 postman 결과 캡쳐
  Pick/src/test/java/com/nob/pick/dailymission/DailyMissionTest.java
  postman/achievement/도전과제 목록 전체 조회.jpg
  postman/achievement/도전과제 삭제.jpg
  postman/achievement/도전과제 수정.jpg
  postman/achievement/도전과제 진행도 증가.jpg
  postman/achievement/도전과제 추가.jpg
  postman/achievement/회원별 도전과제 목록 조회.jpg
  postman/achievement/회원이 달성하지 못한 도전과제 조회.jpg
  postman/achievement/회원이 달성한 도전과제 조회.jpg
  postman/badge/뱃지 목록 전체 조회.jpg
  postman/badge/뱃지 삭제.jpg
  postman/badge/뱃지 수정.jpg
  postman/badge/뱃지 추가.jpg
  postman/badge/뱃지부여 및 레벨 증가.jpg
  postman/badge/챌린지별 뱃지 조회.jpg
  postman/badge/회원이 보유하고있는 뱃지 조회.jpg
  postman/dailymission/일일미션 목록 전체 조회.jpg
  postman/dailymission/일일미션 삭제.jpg
  postman/dailymission/일일미션 수정.jpg
  postman/dailymission/일일미션 추가.jpg
  postman/dailymission/회원별 일일미션 목록 조회.jpg
  postman/dailymission/회원에게 일일미션 부여.jpg
  postman/dailymission/회원이 수행하지 못한 일일미션 조회.jpg
  postman/dailymission/회원이 수행한 일일미션 조회.jpg
Labels: :test_tube: test

#252 [Refactor] server / 잘못 올라간 msaconfig.yml 파일 삭제
  BE14-NoB/config/masconfig.yml
Labels: :bug: bug, 🚨 HOTFIX

#250 [Docs] post / 게시판 도메인 Postman 스크린샷 추가
  postman/post/success/post-01-삭제, 규제되지 않은 글 조회.png
  postman/post/success/post-02-단일 글 및 해당 댓글, 사진 조회-1-1번 게시글 조회.png
  postman/post/success/post-02-단일 글 및 해당 댓글, 사진 조회-2-11번 게시글 조회.png
  postman/post/success/post-02-단일 글 및 해당 댓글, 사진 조회-3-12번 게시글 조회.png
  postman/post/success/post-03-게시글 제목으로 조회-1-1번으로 검색.png
  postman/post/success/post-04-게시글 목록에서 카테고리 별로 조회.png
  postman/post/success/post-05-게시글 등록.png
  postman/post/success/post-06-게시글 삭제(규제된 글).png
  postman/post/success/post-06-게시글 삭제(삭제 성공).png
  postman/post/success/post-06-게시글 삭제(없는 글).png
  postman/post/success/post-06-게시글 삭제(이미 삭제된 글).png
Labels: :page_facing_up: documentation

#242 [Test] post / 삭제 테스트 코드 추가
  Pick/src/main/java/com/nob/pick/post/command/application/controller/CommandPostController.java
  Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostService.java
  Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostServiceImpl.java
  Pick/src/test/java/com/nob/pick/post/DeletePostTest.java
Labels: :test_tube: test

#257 [Chore] report, regulation / insert 관련 결과 메세지 추가
  Pick/src/main/java/com/nob/pick/regulation/command/application/controller/RegulationController.java
  Pick/src/main/java/com/nob/pick/regulation/command/application/service/RegulationImpl.java
  Pick/src/main/java/com/nob/pick/regulation/command/application/service/RegulationService.java
  Pick/src/main/java/com/nob/pick/report/command/application/controller/ReportController.java
Labels: 🔧 refactoring, :zap: Update

#259 [Test] 회원 조회 관련 service 계층 테스트케이스 작성
  BE14-NoB/config/msaconfig.yml
  kick-member/src/main/java/com/nob/kickmember/member/query/dto/MemberProfilePageDTO.java
  kick-member/src/main/resources/com/nob/kickmember/member/query/mapper/MemberMapper.xml
  kick-member/src/test/java/com/nob/kickmember/member/query/service/MemberServiceTest.java
Labels: :test_tube: test

#267 [Hotfix] matching mapper.xml에 핸들러 매핑
  Pick/src/main/resources/com/nob/pick/matching/query/mapper/MatchingMapper.xml
Labels: 🔧 refactoring, 🚨 HOTFIX

#266 [TEST] 프로젝트 관련 도메인 API 테스트 결과 업로드
  Pick/src/main/java/com/nob/pick/common/util/WebSecurity.java
  Pick/src/main/java/com/nob/pick/project/command/application/controller/ReviewController.java
  Pick/src/main/java/com/nob/pick/project/command/application/dto/RequestParticipantDTO.java
  Pick/src/main/java/com/nob/pick/project/command/application/service/ProjectRoomServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/command/application/service/ReviewServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/query/controller/ProjectRoomController.java
  Pick/src/main/java/com/nob/pick/project/query/service/ProjectRoomServiceImpl.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ReponseMeetingVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ReponseParticipantReviewVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseMeetingVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseParticipantVO.java
  Pick/src/main/java/com/nob/pick/project/query/vo/ResponseProjectReviewVO.java
  Pick/src/main/resources/com/nob/pick/project/query/mapper/ParticipantMapper.xml
  Pick/src/test/java/com/nob/pick/project/ProjectRoomTest.java
  document/PICK WBS.png
  postman/project/진행 중인 프로젝트 목록 조회.png
  postman/project/프로젝트 기술 분류 키워드 검색.png
  postman/project/프로젝트 목록 전체 조회.png
  postman/project/프로젝트 방 생성.png
  postman/project/프로젝트 방 입장.png
  postman/project/프로젝트 이름 & 기술 분류 키워드 조회.png
  postman/project/프로젝트 이름 키워드 조회.png
  postman/project/프로젝트 후기 작성.png
  postman/project/프로젝트별 팀원 목록 조회.png
  postman/project/회의록 작성.png
Labels: :test_tube: test

#268 WebSecurity 수정
  Pick/src/main/java/com/nob/pick/common/util/WebSecurity.java
  db/CreateTotalTables.sql
Labels: 🚨 HOTFIX

#270 [Refactor] post / 더미 데이터 Insert문 통합
  db/post/InsertPostDummy.sql
  db/post/comment/InsertDummyComment.sql
  db/post/post/InsertDummyPost.sql
  db/post/postImage/InsertDummyPostImage.sql
Labels: 🔧 refactoring

#271 [doc] / API 명세서 사진 추가
  document/API 명세서.png
Labels: :page_facing_up: documentation

#273 [Doc] git / Readme 날아간거 복구
  README.md
  postman/regulation/규제 등록.png
  postman/regulation/규제 삭제.png
  postman/regulation/모든 규제 목록 조회.png
  postman/regulation/삭제 여부에 따른 규제 목록 조회.png
  postman/regulation/특정 회원 규제 목록 조회.png
  postman/report/모든 신고 목록 조회.png
  postman/report/삭제 여부에 따른 신고 목록 조회.png
  postman/report/상태별 신고 목록 조회.png
  postman/report/신고 내역 삭제.png
  postman/report/신고 등록.png
  postman/report/신고 사유 등록.png
  postman/report/신고 처리 상태 수정.png
  postman/report/특정 회원 신고 목록 조회.png
Labels: :page_facing_up: documentation

#280 Feat: kick-member의 프로필 정보 가져오기 구현
  Pick/src/main/java/com/nob/pick/infrastructure/FeignClientConfig.java
  Pick/src/main/java/com/nob/pick/infrastructure/MemberServiceClient.java
  Pick/src/main/java/com/nob/pick/matching/query/service/MatchingServiceImpl.java
  Pick/src/main/java/com/nob/pick/matching/query/vo/ResponseMemberProfileVO.java
Labels: :sparkles: enhancement

#290 [Feat,Comment,Refacotr] security 주석 추가및 id조회 기능
  kick-member/src/main/java/com/nob/kickmember/common/util/CustomUserDetails.java
  kick-member/src/main/java/com/nob/kickmember/common/util/JwtFilter.java
  kick-member/src/main/java/com/nob/kickmember/common/util/JwtUtil.java
  kick-member/src/main/java/com/nob/kickmember/common/util/WebSecurity.java
  kick-member/src/main/java/com/nob/kickmember/member/query/controller/MemberController.java
  kick-member/src/main/java/com/nob/kickmember/member/query/dto/MemberDTO.java
Labels: :page_facing_up: documentation, :sparkles: enhancement, 🔧 refactoring
